<a href="https://colab.research.google.com/github/Suman18-bit/NLP_CHALANGES/blob/main/One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [29]:
sentence = "The curious cat leapt gracefully onto the windowsill, gazing at the world beyond." # any random text

In [30]:
import nltk

In [31]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [32]:
from nltk.tokenize import word_tokenize

In [33]:
from nltk.corpus import stopwords
import string

punctuation = set(string.punctuation)
sentence_tokens_no_punct = [word for word in sentence_tokens if word not in punctuation]

In [34]:
stop_words = set(stopwords.words('english'))
sentence_tokens_no_stop = [word for word in sentence_tokens_no_punct if word.lower() not in stop_words]

In [35]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [43]:
sentence_tokens = sentence_tokens_no_stop

In [45]:
print(sentence_tokens)

['curious', 'cat', 'leapt', 'gracefully', 'onto', 'windowsill', 'gazing', 'world', 'beyond']


In [46]:
import numpy as np

In [47]:
re_vocab = np.array(sentence_tokens).reshape(-1,1)

In [48]:
print(re_vocab)

[['curious']
 ['cat']
 ['leapt']
 ['gracefully']
 ['onto']
 ['windowsill']
 ['gazing']
 ['world']
 ['beyond']]


In [49]:
OHE = OneHotEncoder(sparse_output=False)

In [50]:
re_vocab_encoded = OHE.fit_transform(re_vocab)

In [52]:
print(re_vocab_encoded)

[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [53]:
for word, encoding in zip(re_vocab, re_vocab_encoded):
    print(f"Word: {word[0]}, Encoding: {encoding}")

Word: curious, Encoding: [0. 0. 1. 0. 0. 0. 0. 0. 0.]
Word: cat, Encoding: [0. 1. 0. 0. 0. 0. 0. 0. 0.]
Word: leapt, Encoding: [0. 0. 0. 0. 0. 1. 0. 0. 0.]
Word: gracefully, Encoding: [0. 0. 0. 0. 1. 0. 0. 0. 0.]
Word: onto, Encoding: [0. 0. 0. 0. 0. 0. 1. 0. 0.]
Word: windowsill, Encoding: [0. 0. 0. 0. 0. 0. 0. 1. 0.]
Word: gazing, Encoding: [0. 0. 0. 1. 0. 0. 0. 0. 0.]
Word: world, Encoding: [0. 0. 0. 0. 0. 0. 0. 0. 1.]
Word: beyond, Encoding: [1. 0. 0. 0. 0. 0. 0. 0. 0.]
